version: '3.1'

services:

        db-agenda:
                container_name: db-agenda-test
                image: postgres:9.6
                restart: always
                environment:
                        POSTGRES_DB: agenda
                        POSTGRES_PASSWORD: 12345
                ports:
                       - 5432:5432
                         

