version: '3.1'

services:

        db-agenda:
                container_name: db-agenda
                image: postgres:9.6
                restart: always
                environment:
                        POSTGRES_DB: agenda
                        POSTGRES_PASSWORD: 12345
                volumes:
                        - ./postgres:/var/lib/postgresql/data
                networks:
                        - agenda
        agenda-backend:
                container_name: agenda-backend
                depends_on:
                        - db-agenda
                build:
                        context: ./agenda-backend
                        args:
                                db_url: db-agenda
                                db_database: agenda
                                db_user: postgres
                                db_password: 12345
                ports:
                        - 8080:8080
                networks:
                        - agenda


networks:
        agenda:

                          

